/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as LobbyIdIndexImport } from "./routes/$lobbyId/index";

// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")();
const LobbyIdAdminLazyImport = createFileRoute("/$lobbyId/admin")();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
	path: "/",
	getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const LobbyIdIndexRoute = LobbyIdIndexImport.update({
	path: "/$lobbyId/",
	getParentRoute: () => rootRoute,
} as any);

const LobbyIdAdminLazyRoute = LobbyIdAdminLazyImport.update({
	path: "/$lobbyId/admin",
	getParentRoute: () => rootRoute,
} as any).lazy(() =>
	import("./routes/$lobbyId/admin.lazy").then((d) => d.Route),
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexLazyImport;
			parentRoute: typeof rootRoute;
		};
		"/$lobbyId/admin": {
			id: "/$lobbyId/admin";
			path: "/$lobbyId/admin";
			fullPath: "/$lobbyId/admin";
			preLoaderRoute: typeof LobbyIdAdminLazyImport;
			parentRoute: typeof rootRoute;
		};
		"/$lobbyId/": {
			id: "/$lobbyId/";
			path: "/$lobbyId";
			fullPath: "/$lobbyId";
			preLoaderRoute: typeof LobbyIdIndexImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	"/": typeof IndexLazyRoute;
	"/$lobbyId/admin": typeof LobbyIdAdminLazyRoute;
	"/$lobbyId": typeof LobbyIdIndexRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexLazyRoute;
	"/$lobbyId/admin": typeof LobbyIdAdminLazyRoute;
	"/$lobbyId": typeof LobbyIdIndexRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexLazyRoute;
	"/$lobbyId/admin": typeof LobbyIdAdminLazyRoute;
	"/$lobbyId/": typeof LobbyIdIndexRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/$lobbyId/admin" | "/$lobbyId";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/$lobbyId/admin" | "/$lobbyId";
	id: "__root__" | "/" | "/$lobbyId/admin" | "/$lobbyId/";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexLazyRoute: typeof IndexLazyRoute;
	LobbyIdAdminLazyRoute: typeof LobbyIdAdminLazyRoute;
	LobbyIdIndexRoute: typeof LobbyIdIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexLazyRoute: IndexLazyRoute,
	LobbyIdAdminLazyRoute: LobbyIdAdminLazyRoute,
	LobbyIdIndexRoute: LobbyIdIndexRoute,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$lobbyId/admin",
        "/$lobbyId/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$lobbyId/admin": {
      "filePath": "$lobbyId/admin.lazy.tsx"
    },
    "/$lobbyId/": {
      "filePath": "$lobbyId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
